### ISSUE TITLE
liqi.py存在致命错误，雀魂的实时对局处理算法更新了

### ISSUE THREAD

**Issue by Pragmatism0220** [747929791/majsoul_wrapper#17]
liqi.py里面第65~66行
```py
B = base64.b64decode(dict_obj['data'])
action_proto_obj = getattr(pb, dict_obj['name']).FromString(B)
```
即获取对局信息，该部分即使使用最新的liqi.json解析也会报错：
```shell
google.protobuf.message.DecodeError: Wrong wire type in tag.
```
我的环境为
```shell
Python 3.9.7
mitmproxy 6.0.2
protobuf 3.14.0（该版本为mitmproxy==6.0.2所依赖的、自动安装的）
protoc 3.14.0
```
目前的雀魂版本为 https://game.maj-soul.net/1/v0.10.174.w/res/proto/liqi.json

**Comment by infinityedge01** [comment]
这是好事，雀魂ai被狠狠制裁了

**Comment by Eric-Joker** [comment]
为什么关闭了 是解决了问题了嘛，能教教我嘛

**Comment by dapiao-zhangwan** [comment]
> 为什么关闭了 是解决了问题了嘛，能教教我嘛

https://github.com/747929791/majsoul_wrapper/issues/27
不知道还需不需要解决，顺手回一个

**Comment by Eric-Joker** [comment]
> #27 不知道还需不需要解决，顺手回一个

感谢（
记得当时刚问完没多久就解决了，现在也不玩了（
