### ISSUE TITLE
liqi.json > liqi.proto 遇到问题

### ISSUE THREAD

**Issue by 1004452714** [747929791/majsoul_wrapper#23]
$npm install -g protobufjs
$pbjs -t proto3 liqi.json > liqi.proto
按照readme里的说明安装了nodejs，然后执行上述命令后报错，个人不了解js，求助
![Snipaste_2023-08-08_18-08-54](https://github.com/747929791/majsoul_wrapper/assets/28773469/4acfd8fd-8137-48d4-b739-ba212d240023)

**Comment by 31-ryougishiki** [comment]
同报错，但是windows
![image](https://github.com/747929791/majsoul_wrapper/assets/77012104/85cbcdc0-5b78-409d-a4e0-f66e5005f153)

**Comment by liting1024** [comment]
建议用nvm安装nodejs，在安装pbjs包后，用pbjs的绝对路径执行命令

**Comment by 1004452714** [comment]
> 建议用nvm安装nodejs，在安装pbjs包后，用pbjs的绝对路径执行命令

感谢，当时确实也是这样解决的
